# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-resource-group: Thrive-Mind-WinApp
#   name: back-load-balancer
# spec:
#   # loadBalancerIP: 52.228.104.55
#   type: LoadBalancer
#   ports:
#     - port: 8080
#   selector:
#     app: thrive-mind-api
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: temp-PI3-resources
  name: thrive-mind-api
spec:
  loadBalancerIP: 52.188.223.13
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: thrive-mind-api
